#include "InputDialog.h"
#include "MainMenu.h"

/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.30                          *
*        Compiled Jul  1 2015, 10:50:32                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END



/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 300)
#define ID_HEADER_0 (GUI_ID_USER + 301)

#define ID_SPINBOX_0 (GUI_ID_USER + 303)




// USER START (Optionally insert additional defines)

static WM_HWIN InputDialog_Handler;
static WM_HWIN Next_Win_Handler;

static int  InputDialog_MenuItemIndex=0;
static int  InputDialog_SetValue=0;

static int InputDialog_Sel_SysItem_Index=0;



// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, InputDialog_Loc_Original_X, InputDialog_Loc_Original_Y, InputDialog_Width, InputDialog_Heigh, 0, 0x0, 0 },
  { HEADER_CreateIndirect, "Header", ID_HEADER_0, 0, 0, 90, 25, 0, 0x0, 0 },
  { SPINBOX_CreateIndirect, "Spinbox", ID_SPINBOX_0, 5, 2, 80, 20, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  WM_HWIN hEdit;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {

  case WM_KEY:

	  switch (((WM_KEY_INFO*)(pMsg->Data.p))->Key)

	  {
	  case	GUI_KEY_ESCAPE:
		   
		  //hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_0);
		  hItem=WM_GetDialogItem(InputDialog_Handler,ID_SPINBOX_0);
		  InputDialog_SetValue=SPINBOX_GetValue(hItem);
		  SysCFG_Set_SysCFG(InputDialog_Sel_SysItem_Index,InputDialog_SetValue);

		 // MainMenu_Get_InputBox(InputDialog_MenuItemIndex,(int)SPINBOX_GetValue(hItem));
		  InputDialog_Hide();



		  break;

	  }
	  break;


  case WM_INIT_DIALOG:

    // Initialization of 'Spinbox'
    //
   hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_0);
	//  hItem=WM_GetDialogItem(InputDialog_Handler,ID_SPINBOX_0);
    SPINBOX_SetFont(hItem, GUI_FONT_COMIC18B_ASCII);
	
    // USER START (Optionally insert additional code for further widget initialization)



	SPINBOX_SetSkin(hItem, SPINBOX_SKIN_FLEX);
	hEdit = SPINBOX_GetEditHandle(hItem);

	
	/* 启用编辑字段的十进制编辑模式 */
	EDIT_SetDecMode(hEdit,
		0,     /* 要修改的值 */
		0,     /* 最小值 */
		999, /* 最大值 */
		1,     /* 如果&gt;0，指定小数点的位置 */
		0);    /* 0（默认值）：在正常模式下编辑，符号仅在Value为负值时显示 */

	
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_HEADER_0: // Notifications sent by 'Header'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_SPINBOX_0: // Notifications sent by 'Spinbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/

WM_HWIN InputDialog_CreateWindow(void) 

{
  

  InputDialog_Handler = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return InputDialog_Handler;
}

// USER START (Optionally insert additional public code)
// USER END

WM_HWIN InputDialog_Show(WM_HWIN	NextHWin,int itemIndex)
{
	WM_HWIN hEdit;
	WM_HWIN hItem;

	 InputDialog_Sel_SysItem_Index=itemIndex;
	 InputDialog_SetValue=SysCFG_Get_SysCFG(InputDialog_Sel_SysItem_Index);
	
	WM_SetDesktopColor(GUI_BLACK);
	
	if (InputDialog_Handler==NULL)
			InputDialog_CreateWindow();
	
	
	else
	{
		WM_BringToTop(InputDialog_Handler);
		WM_ShowWindow(InputDialog_Handler);

	
		
	}
	if (NextHWin!=NULL)
		Next_Win_Handler=NextHWin;
	
	WM_SetFocus(InputDialog_Handler);


	


	

	
	return InputDialog_Handler;
}





void InputDialog_Hide()
{
	if (InputDialog_Handler==NULL)
		InputDialog_CreateWindow();
	else
	{
		//InputDialog_MoveWindow(-1*InputDialog_MenuItemIndex);

		WM_MoveWindow(InputDialog_Handler,0,-1*(InputDialog_MenuItemIndex)*36);

		WM_HideWindow(InputDialog_Handler);
	}
	
	if (Next_Win_Handler!=NULL)
	{
		WM_BringToTop(Next_Win_Handler);
		WM_SetFocus(Next_Win_Handler);
	}
	
	
}

void InputDialog_MoveWindow(int menuItemIndex)
{
	 InputDialog_MenuItemIndex=menuItemIndex;
	WM_MoveWindow(InputDialog_Handler,0,(InputDialog_MenuItemIndex)*36);

}

void InputDialog_SetStyle(int Style)
{
	WM_HWIN hItem;
	WM_HWIN hEdit;

	


	switch (Style)
	{
	case 0:
		hItem=WM_GetDialogItem(InputDialog_Handler,ID_SPINBOX_0);
	
		
		SPINBOX_SetSkin(hItem, SPINBOX_SKIN_FLEX);
		hEdit = SPINBOX_GetEditHandle(hItem);

		InputDialog_SetValue=SysCFG_Get_SysCFG(InputDialog_Sel_SysItem_Index);

		EDIT_SetDecMode(hEdit,
			InputDialog_SetValue,     /* 要修改的值 */
			1,     /* 最小值 */
			31, /* 最大值 */
			0,     /* 如果&gt;0，指定小数点的位置 */
			0);    /* 0（默认值）：在正常模式下编辑，符号仅在Value为负值时显示 */
		 SPINBOX_SetStep(hItem, 1);
	break;

	case 1:
		hItem=WM_GetDialogItem(InputDialog_Handler,ID_SPINBOX_0);


		SPINBOX_SetSkin(hItem, SPINBOX_SKIN_FLEX);
		hEdit = SPINBOX_GetEditHandle(hItem);

		InputDialog_SetValue=SysCFG_Get_SysCFG(InputDialog_Sel_SysItem_Index);

		EDIT_SetDecMode(hEdit,
			InputDialog_SetValue,     /* 要修改的值 */

			0,     /* 最小值 */
			999, /* 最大值 */
			1,     /* 如果&gt;0，指定小数点的位置 */
			0);    /* 0（默认值）：在正常模式下编辑，符号仅在Value为负值时显示 */
		 SPINBOX_SetStep(hItem, 1);
	break;


	}	

}

/*************************** End of file ****************************/
