#include "TimeBox.h"

/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.30                          *
*        Compiled Jul  1 2015, 10:50:32                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "SystemCFG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_HEADER_0 (GUI_ID_USER + 0x01)
#define ID_SPINBOX_0 (GUI_ID_USER + 0x05)
#define ID_SPINBOX_1 (GUI_ID_USER + 0x06)
#define ID_SPINBOX_2 (GUI_ID_USER + 0x0A)


static int TimeBox_MenuItemIndex;

static WM_HWIN TimeBox_Handler;
static WM_HWIN Next_Win_Handler;

static int TimeBox_Style=0;

static int TimeBox_Field0_Index=0;
static int TimeBox_Field0_Value=0;


static int TimeBox_Field1_Index=0;
static int TimeBox_Field1_Value=0;



static int TimeBox_Field2_Index=0;
static int TimeBox_Field2_Value=0;


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, TimeBox_Loc_Original_X, TimeBox_Loc_Original_Y, TimeBox_Width, TimeBox_Heigh, 0, 0x0, 0 },
  { HEADER_CreateIndirect, "Header", ID_HEADER_0, 0, 0, 162, 25, 0, 0x0, 0 },
  { SPINBOX_CreateIndirect, "Spinbox", ID_SPINBOX_0, 2, 2, 63, 20, 0, 0x0, 0 },
  { SPINBOX_CreateIndirect, "Spinbox", ID_SPINBOX_1, 68, 2, 44, 20, 0, 0x0, 0 },
  { SPINBOX_CreateIndirect, "Spinbox", ID_SPINBOX_2, 115, 2, 44, 20, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) 
{
  WM_HWIN hItem;
	WM_HWIN hEdit;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) 
  {

  case WM_KEY:

	  switch (((WM_KEY_INFO*)(pMsg->Data.p))->Key)

	  {
	  case	GUI_KEY_ESCAPE:

		  //hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_0);
		  //hItem=WM_GetDialogItem(InputDialog_Handler,ID_SPINBOX_0);

		  //MainMenu_Get_InputBox(InputDialog_MenuItemIndex,(int)SPINBOX_GetValue(hItem));

		  if(TimeBox_Style==0)
		  {
			  hItem=WM_GetDialogItem(TimeBox_Handler,ID_SPINBOX_0);
			  TimeBox_Field0_Value=SPINBOX_GetValue(hItem);
			  SysCFG_Set_SysCFG(SysCFG_Item_Hour_Index,TimeBox_Field0_Value);

			  hItem=WM_GetDialogItem(TimeBox_Handler,ID_SPINBOX_1);
			  TimeBox_Field1_Value=SPINBOX_GetValue(hItem);
			  SysCFG_Set_SysCFG(SysCFG_Item_Min_Index,TimeBox_Field1_Value);

			  hItem=WM_GetDialogItem(TimeBox_Handler,ID_SPINBOX_2);
			  TimeBox_Field2_Value=SPINBOX_GetValue(hItem);
			  SysCFG_Set_SysCFG(SysCFG_Item_Sec_Index,TimeBox_Field2_Value);
			 
		  }

		  else
		  {
			  hItem=WM_GetDialogItem(TimeBox_Handler,ID_SPINBOX_0);
			  TimeBox_Field0_Value=SPINBOX_GetValue(hItem);
			  SysCFG_Set_SysCFG(SysCFG_Item_Year_Index,TimeBox_Field0_Value);

			  hItem=WM_GetDialogItem(TimeBox_Handler,ID_SPINBOX_1);
			  TimeBox_Field1_Value=SPINBOX_GetValue(hItem);
			  SysCFG_Set_SysCFG(SysCFG_Item_Month_Index,TimeBox_Field1_Value);

			  hItem=WM_GetDialogItem(TimeBox_Handler,ID_SPINBOX_2);
			  TimeBox_Field2_Value=SPINBOX_GetValue(hItem);
			  SysCFG_Set_SysCFG(SysCFG_Item_Day_Index,TimeBox_Field2_Value);
		  }

		 TimeBox_Hide();



		  break;

	  }
	  break;
  case WM_INIT_DIALOG:
    //
    // Initialization of 'year Spinbox'
    //
	  TimeBox_Style=1;
    hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_0);
    SPINBOX_SetFont(hItem, GUI_FONT_COMIC18B_ASCII);

    SPINBOX_SetSkin(hItem, SPINBOX_SKIN_FLEX);
	hEdit = SPINBOX_GetEditHandle(hItem);
	/* 启用编辑字段的十进制编辑模式 */
	EDIT_SetDecMode(hEdit,
		2000,     /* 要修改的值 */
		2000,     /* 最小值 */
		2999, /* 最大值 */
		0,     /* 如果&gt;0，指定小数点的位置 */
		0);    /* 0（默认值）：在正常模式下编辑，符号仅在Value为负值时显示 */
    //
    // Initialization of 'month Spinbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_1);
    SPINBOX_SetFont(hItem, GUI_FONT_COMIC18B_ASCII);
    SPINBOX_SetSkin(hItem, SPINBOX_SKIN_FLEX);
	hEdit = SPINBOX_GetEditHandle(hItem);
	/* 启用编辑字段的十进制编辑模式 */
	EDIT_SetDecMode(hEdit,
		1,     /* 要修改的值 */
		1,     /* 最小值 */
		12, /* 最大值 */
		0,     /* 如果&gt;0，指定小数点的位置 */
		0);    /* 0（默认值）：在正常模式下编辑，符号仅在Value为负值时显示 */
    //
    // Initialization of 'day Spinbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_2);
    SPINBOX_SetFont(hItem, GUI_FONT_COMIC18B_ASCII);
    SPINBOX_SetSkin(hItem, SPINBOX_SKIN_FLEX);
	hEdit = SPINBOX_GetEditHandle(hItem);
	/* 启用编辑字段的十进制编辑模式 */
	EDIT_SetDecMode(hEdit,
		1,     /* 要修改的值 */
		1,     /* 最小值 */
		31, /* 最大值 */
		0,     /* 如果&gt;0，指定小数点的位置 */
		0);    /* 0（默认值）：在正常模式下编辑，符号仅在Value为负值时显示 */
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_HEADER_0: // Notifications sent by 'Header'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_SPINBOX_0: // Notifications sent by 'Spinbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_SPINBOX_1: // Notifications sent by 'Spinbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_SPINBOX_2: // Notifications sent by 'Spinbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/

WM_HWIN TimeBox_CreateWindow(void) 
{
  

 TimeBox_Handler = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return TimeBox_Handler;
}

// USER START (Optionally insert additional public code)

void TimeBox_MoveWindow(int menuItemIndex)
{
	TimeBox_MenuItemIndex=menuItemIndex;
	WM_MoveWindow(TimeBox_Handler,0,(TimeBox_MenuItemIndex+1)*32);
}


WM_HWIN TimeBox_Show(WM_HWIN	NextHWin,int boxMode)
{
	
	if (boxMode==0)
	{

		TimeBox_Field0_Index=SysCFG_Item_Hour_Index;
		TimeBox_Field1_Index=SysCFG_Item_Min_Index;
		TimeBox_Field2_Index=SysCFG_Item_Sec_Index;

	
	
	}
	else
	{
		TimeBox_Field0_Index=SysCFG_Item_Year_Index;
		TimeBox_Field1_Index=SysCFG_Item_Month_Index;
		TimeBox_Field2_Index=SysCFG_Item_Day_Index;


	}


	
	WM_SetDesktopColor(GUI_BLACK);
	
	if (TimeBox_Handler==NULL)
			TimeBox_CreateWindow();
	
	
	else
	{
		WM_BringToTop(TimeBox_Handler);
		WM_ShowWindow(TimeBox_Handler);
		
	}
	if (NextHWin!=NULL)
		Next_Win_Handler=NextHWin;
	
	WM_SetFocus(TimeBox_Handler);
	
	return TimeBox_Handler;
}





void TimeBox_Hide()
{
	if (TimeBox_Handler==NULL)
		TimeBox_CreateWindow();
	else
	{
		//TimeBox_MoveWindow(-1*TimeBox_MenuItemIndex);

		WM_MoveWindow(TimeBox_Handler,0,-1*(TimeBox_MenuItemIndex+1)*32);

		WM_HideWindow(TimeBox_Handler);
	}
	
	if (Next_Win_Handler!=NULL)
	{
		WM_BringToTop(Next_Win_Handler);
		WM_SetFocus(Next_Win_Handler);
	}
	
	
}



void TimeBox_SetStyle(int Style)
{
	WM_HWIN hItem;
	WM_HWIN hEdit;
	switch (Style)
	{
	case 0:
		if (TimeBox_Style==1)

			WM_ResizeWindow(TimeBox_Handler,-19,0);

		hItem = WM_GetDialogItem(TimeBox_Handler, ID_SPINBOX_0);
		if (TimeBox_Style==1)
			WM_ResizeWindow(hItem,-19,0);
		hEdit = SPINBOX_GetEditHandle(hItem);

		TimeBox_Field0_Value=SysCFG_Get_SysCFG(TimeBox_Field0_Index);


		if (TimeBox_Style==1)
			WM_ResizeWindow(hEdit,-19,0);
		/* 启用编辑字段的十进制编辑模式 */
		EDIT_SetDecMode(hEdit,
			TimeBox_Field0_Value,     /* 要修改的值 */
			0,     /* 最小值 */
			24, /* 最大值 */
			0,     /* 如果&gt;0，指定小数点的位置 */
			0);    /* 0（默认值）：在正常模式下编辑，符号仅在Value为负值时显示 */
		//
		// Initialization of 'month Spinbox'
		//
		hItem = WM_GetDialogItem(TimeBox_Handler, ID_SPINBOX_1);
		if (TimeBox_Style==1)
			WM_MoveWindow(hItem,-19,0);
	
	
		hEdit = SPINBOX_GetEditHandle(hItem);

		TimeBox_Field1_Value=SysCFG_Get_SysCFG(TimeBox_Field1_Index);
		/* 启用编辑字段的十进制编辑模式 */
		EDIT_SetDecMode(hEdit,
			TimeBox_Field1_Value,     /* 要修改的值 */
			0,     /* 最小值 */
			60, /* 最大值 */
			0,     /* 如果&gt;0，指定小数点的位置 */
			0);    /* 0（默认值）：在正常模式下编辑，符号仅在Value为负值时显示 */
		//
		// Initialization of 'day Spinbox'
		//
		hItem = WM_GetDialogItem(TimeBox_Handler, ID_SPINBOX_2);
		if (TimeBox_Style==1)
			WM_MoveWindow(hItem,-19,0);

		
	

		hEdit = SPINBOX_GetEditHandle(hItem);

		TimeBox_Field2_Value=SysCFG_Get_SysCFG(TimeBox_Field2_Index);
		/* 启用编辑字段的十进制编辑模式 */
		EDIT_SetDecMode(hEdit,
			TimeBox_Field2_Value,     /* 要修改的值 */
			0,     /* 最小值 */
			60, /* 最大值 */
			0,     /* 如果&gt;0，指定小数点的位置 */
			0);    /* 0（默认值）：在正常模式下编辑，符号仅在Value为负值时显示 */

		TimeBox_Style=0;
		break;

	case 1:

		if (TimeBox_Style==0)
			WM_ResizeWindow(TimeBox_Handler,19,0);

		hItem = WM_GetDialogItem(TimeBox_Handler, ID_SPINBOX_0);
		if (TimeBox_Style==0)
			WM_ResizeWindow(hItem,19,0);
		

	
		hEdit = SPINBOX_GetEditHandle(hItem);
		if (TimeBox_Style==0)
			WM_ResizeWindow(hEdit,19,0);

		TimeBox_Field0_Value=SysCFG_Get_SysCFG(TimeBox_Field0_Index);
		/* 启用编辑字段的十进制编辑模式 */
		EDIT_SetDecMode(hEdit,
			TimeBox_Field0_Value,     /* 要修改的值 */
			2000,     /* 最小值 */
			2999, /* 最大值 */
			0,     /* 如果&gt;0，指定小数点的位置 */
			0);    /* 0（默认值）：在正常模式下编辑，符号仅在Value为负值时显示 */
		//
		// Initialization of 'month Spinbox'
		//
		hItem = WM_GetDialogItem(TimeBox_Handler, ID_SPINBOX_1);
		if (TimeBox_Style==0)
			WM_MoveWindow(hItem,19,0);
		hEdit = SPINBOX_GetEditHandle(hItem);
		TimeBox_Field1_Value=SysCFG_Get_SysCFG(TimeBox_Field1_Index);
		/* 启用编辑字段的十进制编辑模式 */
		EDIT_SetDecMode(hEdit,
			TimeBox_Field1_Value,     /* 要修改的值 */
			1,     /* 最小值 */
			12, /* 最大值 */
			0,     /* 如果&gt;0，指定小数点的位置 */
			0);    /* 0（默认值）：在正常模式下编辑，符号仅在Value为负值时显示 */
		//
		// Initialization of 'day Spinbox'
		//
		hItem = WM_GetDialogItem(TimeBox_Handler, ID_SPINBOX_2);
		if (TimeBox_Style==0)
			WM_MoveWindow(hItem,19,0);
	
		hEdit = SPINBOX_GetEditHandle(hItem);

		TimeBox_Field2_Value=SysCFG_Get_SysCFG(TimeBox_Field2_Index);
		/* 启用编辑字段的十进制编辑模式 */
		EDIT_SetDecMode(hEdit,
			TimeBox_Field2_Value,     /* 要修改的值 */
			1,     /* 最小值 */
			31, /* 最大值 */
			0,     /* 如果&gt;0，指定小数点的位置 */
			0);    /* 0（默认值）：在正常模式下编辑，符号仅在Value为负值时显示 */

		TimeBox_Style=1;
		break;


	}	

}


// USER END

/*************************** End of file ****************************/
